extends "res://Battle/Apply.gd"
class_name STATS


# Status effects
enum{CONFUSION, POISON, BURN, SLOW, HASTE, BERSERK, 
REGEN, UNDEAD, PETRIFY, SILENCE, BLIND, DOOM, PARALYSIS, 
MAX_HP_DOWN, MAX_MP_DOWN, SLEEP, FLOAT, UNKILLABLE, 
INVISIBILITY, REFLECT, CONTROL, CHARM, HP_CRITICAL, CURSE, 
STOP, HIDDEN, FREEZE, IMMOBILIZE, KO, VEIL, TRAPPED}